### PR TITLE
Fixed compiler error by reverting to FONA use.

### PR DESCRIPTION
**Pull request by bendory**

### CODE REVIEW

**Comment by botletics** [comment]
Even this won't compile because the Adafruit_FONA library doesn't have an Adafruit_FONA_LTE class.

**Comment by bendory** [comment]
Now I'm sad. 😢

**Comment by botletics** [comment]
Me too 😓 I'd hate to just delete that example though... Perhaps a tacky workaround is to point to the release in the old repo and tell them to use that Botletics Adafruit_FONA library, in conjunction with the Botletics-SIM7000 library?

**Comment by botletics** [comment]
Yea it's tacky but it works. I wrote a note in the AdafruitIO_MQTT_Demo sketch on how to do that.

**Pull request merged**
