### PR TITLE
Prepared for Arduino library submission.

### PR DESCRIPTION
**Pull request by bendory**
Added `keywords.txt`.

Cleaned up Lint issues, specifically:
- added LICENSE
- renamed library to BotleticsSIM7000
- renamed Adafruit_FONA.* library files to BotleticsSIM7000.*
- fixed includes to include new library header

The library now lints clean using [arduino-lint](https://github.com/arduino/arduino-lint) in `strict` mode.

_After_ this PR is merged, please tag a release `1.0.0` which will be our first submission to the Arduino library. (If you want to invite me to join the repo, I'm happy to pitch in and set that up.)

### CODE REVIEW

**Comment by bendory** [comment]
🤔 Perhaps rename the Github repo to `Botletics-SIM7000` rather than `SIM7000-Shield-Library`? If you want to do this, we should do it prior to my submission to Arduino.

To rename: click on the settings button, the repository name is at the top, just rename it. Github provides convenient redirects from the existing repo name to the new repo name for some period of time.

**Comment by bendory** [comment]
Ref: https://github.com/bendory/SIM7000-Shield-Library/issues/2

**Comment by bendory** [comment]
https://github.com/bendory/SIM7000-Shield-Library/issues/1

**Comment by botletics** [comment]
Thanks a ton!

**Comment by botletics** [comment]
Done deal, I created a release 1.0.0 and renamed the repo.

**Pull request merged**
